"""empty message

Revision ID: 939d8cb0824c
Revises: 1a5580415f0c
Create Date: 2022-05-19 01:48:55.177468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939d8cb0824c'
down_revision = '1a5580415f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('colors', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image_1', sa.String(length=150), nullable=False),
    sa.Column('image_2', sa.String(length=150), nullable=False),
    sa.Column('image_3', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addproduct')
    # ### end Alembic commands ###
